### PR TITLE
Added SuBuiltinClass to handle Class static methods and instantiating built-in elements

### PR DESCRIPTION
**Pull request by Hao-Axon**

### CODE REVIEW

**Comment by apmckinlay** [comment]
You know the code better than me, but would it be possible to make the builtin classes like Date be prototypes so that Object.create(clas) will still work?

**Comment by Hao-Axon** [comment]
The way I figured out is to use Object.setPrototypeOf to change the prototype of the instance created by Object.create(clas) to the right prototype (SuDate.prototype) and then initialize it. 

It avoids the extra check in su.instanticate function. However, [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf)  says that 

> Changing the [[Prototype]] of an object is, by the nature of how modern JavaScript engines optimize property accesses, a very slow operation, in every browser and JavaScript engine. 

It might be Okay considering how rarely do we use "new" to instantiate a built-in class.

**Comment by apmckinlay** [comment]
Seems reasonable. Speed might not be as bad since we're changing the prototype before we use the object.

Another option might be to change: `instance = Object.create(clas)`

to something like: `clas.instantiate()`

**Comment by Hao-Axon** [comment]
Changed to use `clas.instantiate()` to handle Instance creation so that SuBuiltinClass can bind a different class to the created object.

Please have a look, but please don't merge this pull request. I can make another pull request with clear commit history after we decide which changes we want.

**Pull request closed without merging**
